POST https://localhost:7211/User/Authenticate
Content-Type: application/json

{
  "username": "adminuser",
  "password": "admin"
}

###

POST https://localhost:7211/User/RefToken
Content-Type: application/json

{
  "jwttoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW51c2VyIiwicm9sZSI6ImFkbWluIiwibmJmIjoxNjY4NTkwMTQ0LCJleHAiOjE2Njg1OTAxNjMsImlhdCI6MTY2ODU5MDE0NH0.cmEI8TMjXGOJTp-uTNlf7OqPVfY1JbkoP_cD39OzWVA",
  "refreshtoken": "7xZ6WBXRfHdIdUZvu3+x554kS3RtEE5gsuZHM7Gzyek="
}

###

GET https://localhost:7211/Products/GetAll
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW51c2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJuYmYiOjE2Njg1OTAxNDQsImV4cCI6MTY2ODU5MDI2OSwiaWF0IjoxNjY4NTkwMTQ0fQ.igdIV2giiGzHIV8uO6vYLEhOr19DnRyqslU-iNH0jp0

###
GET https://localhost:7211/Products/GetByCode/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW51c2VyIiwicm9sZSI6ImFkbWluIiwibmJmIjoxNjY4NDE3Njg2LCJleHAiOjE2Njg0MTc3MDYsImlhdCI6MTY2ODQxNzY4Nn0.MZ31evkKmRsP23jK6WQO65Ja3BRfJAIU_NuKh4oa8ek


### 
POST https://localhost:7211/Create
Content-Type: application/json

{

}


### 
DELETE  https://localhost:7211/Remove/1
